const data = [
    
            [
                "porttitor.scelerisque@sodales.co.uk",
                "Quentin",
                "048-888-4767"
            ],
            [
                "Sed.eget@in.net",
                "Ethan",
                "046-968-9107"
            ],
            [
                "Nam.ligula.elit@liberonecligula.co.uk",
                "Fulton",
                "013-202-8740"
            ],
            [
                "libero.lacus@Donecfeugiat.net",
                "Noah",
                "039-234-5077"
            ],
            [
                "metus.Aliquam@rhoncusNullamvelit.edu",
                "Marvin",
                "036-406-7365"
            ],
            [
                "risus.Quisque@dapibus.com",
                "Hilary",
                "096-122-0052"
            ],
            [
                "pede@Nam.org",
                "Ryan",
                "080-210-1957"
            ],
            [
                "nisi@feugiatSednec.com",
                "Brandon",
                "091-232-7709"
            ],
            [
                "Morbi@commodoatlibero.org",
                "Odysseus",
                "008-312-8519"
            ],
            [
                "sit.amet@lacusNullatincidunt.edu",
                "Julie",
                "001-636-4647"
            ],
            [
                "rhoncus.Donec.est@quispede.ca",
                "Moses",
                "014-783-0114"
            ],
            [
                "eget.dictum.placerat@ametnulla.edu",
                "Cassidy",
                "067-993-5816"
            ],
            [
                "Fusce.mi.lorem@Nunclaoreetlectus.ca",
                "Arthur",
                "010-897-7245"
            ],
            [
                "egestas.urna.justo@Mauris.org",
                "Geoffrey",
                "078-658-3062"
            ],
            [
                "arcu.Nunc@diamDuismi.com",
                "Debra",
                "045-539-6734"
            ],
            [
                "sapien.Nunc@ipsumprimis.org",
                "Destiny",
                "098-522-8614"
            ],
            [
                "ut.nisi@purusNullamscelerisque.com",
                "Stephen",
                "047-276-1391"
            ],
            [
                "nascetur.ridiculus@convallisconvallis.net",
                "Xyla",
                "094-239-2434"
            ],
            [
                "posuere@diamvelarcu.org",
                "Pearl",
                "050-117-7893"
            ],
            [
                "feugiat.Sed@ullamcorper.edu",
                "Nash",
                "062-378-0871"
            ],
            [
                "Integer.urna@malesuadaiderat.net",
                "Daryl",
                "087-038-0990"
            ]
]

module.exports  = data;

